"""add apply column to user_sapiens

Revision ID: 50b3e27c6572
Revises: 
Create Date: 2024-10-23 22:05:29.962792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b3e27c6572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sapiens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sapiens', schema=None) as batch_op:
        batch_op.drop_column('apply')

    # ### end Alembic commands ###
