"""Add image_url column to PostSapiens

Revision ID: aaa28585d32b
Revises: 50b3e27c6572
Create Date: 2024-10-24 21:55:54.913260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa28585d32b'
down_revision = '50b3e27c6572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_sapiens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_sapiens', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
